### PR TITLE
Preparing for 1.2.3 release with mzTab output

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
 - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/diaproteomics/tree/master/.github/CONTRIBUTING.md)
 - [x] If necessary, also make a PR on the nf-core/diaproteomics _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint .`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Test files?

**Comment by Leon-Bichmann** [comment]
so the test now includes also generating the mzTab

**Comment by Leon-Bichmann** [comment]
See for example the normal test log
```
...
[8d/af2bb8] Submitted process > export_of_scoring_results (1)
[d6/d2fa2c] Submitted process > export_of_scoring_results (2)
[25/1911f3] Submitted process > chromatogram_alignment (2)
[96/1782f9] Submitted process > chromatogram_alignment (1)
[91/a109bb] Submitted process > mztab_export (1)
[75/722758] Submitted process > mztab_export (2)
WARN: [nf-core/diaproteomics] Could not attach MultiQC report to summary email
-[nf-core/diaproteomics] Pipeline completed successfully-
```

**Comment by Leon-Bichmann** [comment]
And this is what it looks like:
https://github.com/nf-core/test-datasets/blob/diaproteomics/Study_2_Benign.mzTab

**Comment by timosachsenberg** [comment]
Thanks. see p.10 ff https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-releases/1_0-Proteomics-Release/mzTab_format_specification.pdf
for mandatory entries

**Comment by Leon-Bichmann** [comment]
I don't think it will be possible now to add all these entries, nor do I take them as input to the workflow. Maybe one could expand on this in the future, I would rather take this as a "mzTab-like" output, also since many of the entries for DIA are not yet supported by PSI...

**Comment by Leon-Bichmann** [comment]
What do you think? If there are any rather simple fields I can still add them of course, but I don't think all of them are really necessary in this case.

**Comment by timosachsenberg** [comment]
hmm yeah I am not sure if you can do more about it. Can you pull in the experimental design information/source files etc. and annotate those?

**Comment by Leon-Bichmann** [comment]
I added the MSstats_BioReplicate column to the input spreadsheet:
Screen Shot 2021-04-20 at 09 17 00

**Pull request merged**
